#ifndef WHIS_KEYMAP_H
#define WHIS_KEYMAP_H

#include <stdbool.h>
#include <stdint.h>

/* 00 (Reserved) */
#define WHIS_KEY_RESERVED (0x00)
#define WHIS_KEY_ERRROLLOVR (0x01)
#define WHIS_KEY_POSTFAIL (0x02)
#define WHIS_KEY_ERRUNDEF (0x03)
#define WHIS_KEY_A (0x04)
#define WHIS_KEY_B (0x05)
#define WHIS_KEY_C (0x06)
#define WHIS_KEY_D (0x07)
#define WHIS_KEY_E (0x08)
#define WHIS_KEY_F (0x09)
#define WHIS_KEY_G (0x0A)
#define WHIS_KEY_H (0x0B)
#define WHIS_KEY_I (0x0C)
#define WHIS_KEY_J (0x0D)
#define WHIS_KEY_K (0x0E)
#define WHIS_KEY_L (0x0F)
#define WHIS_KEY_M (0x10)
#define WHIS_KEY_N (0x11)
#define WHIS_KEY_O (0x12)
#define WHIS_KEY_P (0x13)
#define WHIS_KEY_Q (0x14)
#define WHIS_KEY_R (0x15)
#define WHIS_KEY_S (0x16)
#define WHIS_KEY_T (0x17)
#define WHIS_KEY_U (0x18)
#define WHIS_KEY_V (0x19)
#define WHIS_KEY_W (0x1A)
#define WHIS_KEY_X (0x1B)
#define WHIS_KEY_Y (0x1C)
#define WHIS_KEY_Z (0x1D)
#define WHIS_KEY_1 (0x1E)
#define WHIS_KEY_2 (0x1F)
#define WHIS_KEY_3 (0x20)
#define WHIS_KEY_4 (0x21)
#define WHIS_KEY_5 (0x22)
#define WHIS_KEY_6 (0x23)
#define WHIS_KEY_7 (0x24)
#define WHIS_KEY_8 (0x25)
#define WHIS_KEY_9 (0x26)
#define WHIS_KEY_0 (0x27)
#define WHIS_KEY_RET (0x28)
#define WHIS_KEY_ESC (0x29)
#define WHIS_KEY_DEL (0x2A)
#define WHIS_KEY_TAB (0x2B)
#define WHIS_KEY_SPC (0x2C)
#define WHIS_KEY_MIN (0x2D)
#define WHIS_KEY_EQL (0x2E)
#define WHIS_KEY_LFTSQBRK (0x2F)
#define WHIS_KEY_RGTSQBRK (0x30)
#define WHIS_KEY_BKSLASH (0x31)
#define WHIS_KEY_NUSHASH (0x32)
#define WHIS_KEY_SEMICLN (0x33)
#define WHIS_KEY_SGLQUOTE (0x34)
#define WHIS_KEY_GRAVE (0x35)
#define WHIS_KEY_COMMA (0x36)
#define WHIS_KEY_DOT (0x37)
#define WHIS_KEY_FWSLASH (0x38)
#define WHIS_KEY_CAPSLOCK (0x39)
#define WHIS_KEY_F1 (0x3A)
#define WHIS_KEY_F2 (0x3B)
#define WHIS_KEY_F3 (0x3C)
#define WHIS_KEY_F4 (0x3D)
#define WHIS_KEY_F5 (0x3E)
#define WHIS_KEY_F6 (0x3F)
#define WHIS_KEY_F7 (0x40)
#define WHIS_KEY_F8 (0x41)
#define WHIS_KEY_F9 (0x42)
#define WHIS_KEY_F10 (0x43)
#define WHIS_KEY_F11 (0x44)
#define WHIS_KEY_F12 (0x45)
#define WHIS_KEY_PRTSCR (0x46)
#define WHIS_KEY_SCROLLLCK (0x47)
#define WHIS_KEY_PAUSE (0x48)
#define WHIS_KEY_INS (0x49)
#define WHIS_KEY_HOME (0x4A)
#define WHIS_KEY_PAGEUP (0x4B)
#define WHIS_KEY_DELFW (0x4C)
#define WHIS_KEY_END (0x4D)
#define WHIS_KEY_PAGEDN (0x4E)
#define WHIS_KEY_RGTARROW (0x4F)
#define WHIS_KEY_LFTARROW (0x50)
#define WHIS_KEY_DNARROW (0x51)
#define WHIS_KEY_UPARROW (0x52)
#define WHIS_KEY_PAD_NUMLCK (0x53)
#define WHIS_KEY_PAD_FWSLASH (0x54)
#define WHIS_KEY_PAD_ASTR (0x55)
#define WHIS_KEY_PAD_MIN (0x56)
#define WHIS_KEY_PAD_ADD (0x57)
#define WHIS_KEY_PAD_RET (0x58)
#define WHIS_KEY_PAD_1 (0x59)
#define WHIS_KEY_PAD_2 (0x5A)
#define WHIS_KEY_PAD_3 (0x5B)
#define WHIS_KEY_PAD_4 (0x5C)
#define WHIS_KEY_PAD_5 (0x5D)
#define WHIS_KEY_PAD_6 (0x5E)
#define WHIS_KEY_PAD_7 (0x5F)
#define WHIS_KEY_PAD_8 (0x60)
#define WHIS_KEY_PAD_9 (0x61)
#define WHIS_KEY_PAD_0 (0x62)
#define WHIS_KEY_PAD_DOT (0x63)
#define WHIS_KEY_NUSBKSLASH (0x64)
#define WHIS_KEY_APP (0x65)
#define WHIS_KEY_PAD_POW (0x66)
#define WHIS_KEY_PAD_EQL (0x67)
#define WHIS_KEY_F13 (0x68)
#define WHIS_KEY_F14 (0x69)
#define WHIS_KEY_F15 (0x6A)
#define WHIS_KEY_F16 (0x6B)
#define WHIS_KEY_F17 (0x6C)
#define WHIS_KEY_F18 (0x6D)
#define WHIS_KEY_F19 (0x6E)
#define WHIS_KEY_F20 (0x6F)
#define WHIS_KEY_F21 (0x70)
#define WHIS_KEY_F22 (0x71)
#define WHIS_KEY_F23 (0x72)
#define WHIS_KEY_F24 (0x73)
#define WHIS_KEY_EXEC (0x74)
#define WHIS_KEY_HELP (0x75)
#define WHIS_KEY_MENU (0x76)
#define WHIS_KEY_SELECT (0x77)
#define WHIS_KEY_STOP (0x78)
#define WHIS_KEY_AGAIN (0x79)
#define WHIS_KEY_UNDO (0x7A)
#define WHIS_KEY_CUT (0x7B)
#define WHIS_KEY_COPY (0x7C)
#define WHIS_KEY_PASTE (0x7D)
#define WHIS_KEY_FIND (0x7E)
#define WHIS_KEY_MUTE (0x7F)
#define WHIS_KEY_VOLUP (0x80)
#define WHIS_KEY_VOLDN (0x81)
#define WHIS_KEY_LCKCAPSLCK (0x82)
#define WHIS_KEY_LCKSCROLLLCK (0x83)
#define WHIS_KEY_LCKNUMLCK (0x84)
#define WHIS_KEY_PAD_COMMA (0x85)
#define WHIS_KEY_PAD_EQLSGN (0x86)
#define WHIS_KEY_INTN1 (0x87)
#define WHIS_KEY_INTN2 (0x88)
#define WHIS_KEY_INTN3 (0x89)
#define WHIS_KEY_INTN4 (0x8A)
#define WHIS_KEY_INTN5 (0x8B)
#define WHIS_KEY_INTN6 (0x8C)
#define WHIS_KEY_INTN7 (0x8D)
#define WHIS_KEY_INTN8 (0x8E)
#define WHIS_KEY_INTN9 (0x8F)
#define WHIS_KEY_LANG1 (0x90)
#define WHIS_KEY_LANG2 (0x91)
#define WHIS_KEY_LANG3 (0x92)
#define WHIS_KEY_LANG4 (0x93)
#define WHIS_KEY_LANG5 (0x94)
#define WHIS_KEY_LANG6 (0x95)
#define WHIS_KEY_LANG7 (0x96)
#define WHIS_KEY_LANG8 (0x97)
#define WHIS_KEY_LANG9 (0x98)
#define WHIS_KEY_ALTERS (0x99)
#define WHIS_KEY_SYSREQ (0x9A)
#define WHIS_KEY_CANCEL (0x9B)
#define WHIS_KEY_CLR (0x9C)
#define WHIS_KEY_PRIOR (0x9D)
#define WHIS_KEY_RET2 (0x9E)
#define WHIS_KEY_SEP (0x9F)
#define WHIS_KEY_OUT (0xA0)
#define WHIS_KEY_OPER (0xA1)
#define WHIS_KEY_CLR2 (0xA2)
#define WHIS_KEY_CRSEL (0xA3)
#define WHIS_KEY_EXSEL (0xA4)
/* No A5-AF (Reserved) */
#define WHIS_KEY_PAD_00 (0xB0)
#define WHIS_KEY_PAD_000 (0xB1)
#define WHIS_KEY_THOUSEP (0xB2)
#define WHIS_KEY_DECSEP (0xB3)
#define WHIS_KEY_CURRUNIT (0xB4)
#define WHIS_KEY_CURRSUBUNIT (0xB5)
#define WHIS_KEY_PAD_LFTRDBRK (0xB6)
#define WHIS_KEY_PAD_RGTRDBRK (0xB7)
#define WHIS_KEY_PAD_LFTSQBRK (0xB8)
#define WHIS_KEY_PAD_RGTSQBRK (0xB9)
#define WHIS_KEY_PAD_TAB (0xBA)
#define WHIS_KEY_PAD_BKSPC (0xBB)
#define WHIS_KEY_PAD_A (0xBC)
#define WHIS_KEY_PAD_B (0xBD)
#define WHIS_KEY_PAD_C (0xBE)
#define WHIS_KEY_PAD_D (0xBF)
#define WHIS_KEY_PAD_E (0xC0)
#define WHIS_KEY_PAD_F (0xC1)
#define WHIS_KEY_PAD_XOR (0xC2)
#define WHIS_KEY_PAD_CARET (0xC3)
#define WHIS_KEY_PAD_PERCENT (0xC4)
#define WHIS_KEY_PAD_LSTHAN (0xC5)
#define WHIS_KEY_PAD_GRTHAN (0xC6)
#define WHIS_KEY_PAD_APM (0xC7)
#define WHIS_KEY_PAD_DBLAMP (0xC8)
#define WHIS_KEY_PAD_VBAR (0xC9)
#define WHIS_KEY_PAD_DBLVBAR (0xCA)
#define WHIS_KEY_PAD_CLN (0xCB)
#define WHIS_KEY_PAD_HASH (0xCC)
#define WHIS_KEY_PAD_SPC (0xCD)
#define WHIS_KEY_PAD_AT (0xCE)
#define WHIS_KEY_PAD_EXCLAIM (0xCF)
#define WHIS_KEY_PAD_MEMSTORE (0xD0)
#define WHIS_KEY_PAD_MEMRECALL (0xD1)
#define WHIS_KEY_PAD_MEMCLR (0xD2)
#define WHIS_KEY_PAD_MEMADD (0xD3)
#define WHIS_KEY_PAD_MEMSUB (0xD4)
#define WHIS_KEY_PAD_MEMMUL (0xD5)
#define WHIS_KEY_PAD_MEMDIV (0xD6)
#define WHIS_KEY_PAD_PLUSMIN (0xD7)
#define WHIS_KEY_PAD_CLR (0xD8)
#define WHIS_KEY_PAD_CLRENT (0xD9)
#define WHIS_KEY_PAD_BIN (0xDA)
#define WHIS_KEY_PAD_OCT (0xDB)
#define WHIS_KEY_PAD_DEC (0xDC)
#define WHIS_KEY_PAD_HEX (0xDD)
/* No DE-DF (Reserved) */
#define WHIS_KEY_LFTCTL (0xE0)
#define WHIS_KEY_LFTSHIFT (0xE1)
#define WHIS_KEY_LFTALT (0xE2)
#define WHIS_KEY_LFTGUI (0xE3)
#define WHIS_KEY_RGTCTL (0xE4)
#define WHIS_KEY_RGTSHIFT (0xE5)
#define WHIS_KEY_RGTALT (0xE6)
#define WHIS_KEY_RGTGUI (0xE7)

typedef uint16_t wh_keycode;

#define WHIS_KEY2BTN_OFFSET (0x09)
#define WHIS_ZR2BTN_OFFSET (0xEF)

#define WHIS_BTN_1 (0xF0) /* Mouse left */
#define WHIS_BTN_2 (0xF1) /* Mouse right */
#define WHIS_BTN_3 (0xF2) /* Mouse middle */
#define WHIS_BTN_SCROLLUP (0xF3)
#define WHIS_BTN_SCROLLDN (0XF4)
#define WHIS_BTN_4 (0xF5) /* MB4 */
#define WHIS_BTN_5 (0xF6) /* MB5 */
#define WHIS_BTN_X (0xFF) /* MBX */

typedef uint16_t wh_btncode;

#define WHIS_KEY_ALPHANUM(keycode) \
	((keycode) >= WHIS_KEY_A && ((keycode) <= WHIS_KEY_0 || (keycode) >= WHIS_KEY_PAD_1 && (keycode) <= WHIS_KEY_PAD_0))

#define WHIS_KEY_ALPHA(keycode) \
	((keycode) >= WHIS_KEY_A && (keycode) <= WHIS_KEY_Z)

#define WHIS_KEY_NUM(keycode) \
	((keycode) >= WHIS_KEY_1 && (keycode) <= WHIS_KEY_0 || (keycode) >= WHIS_KEY_PAD_1 && (keycode) <= WHIS_KEY_PAD_0)

#endif /* WHIS_KEYMAP_H */
